// Function to open the modal and display the emoji and its name
function searchEmoji() {
    const emojiInput = document.getElementById('emoji-search').value;
    const emojiName = getEmojiName(emojiInput);

    if (emojiName) {
        openModal(emojiInput, emojiName); // Pass both emoji and name to openModal
    } else {
        openModal("😢", "Sorry! I was too dumb to not add it"); // Display the 'not found' emoji and message
    }
}

// Function to get the name of an emoji (you can add more mappings as needed)
function getEmojiName(emoji) {
    const emojiMap = {
        '✅': ['tick', 'correct'],
        '❌': ['wrong', 'incorrect'],
        '😀': ['smile'],
        '😂': ['laugh'],
        '❤️': ['heart'],
        '😉': ['wink', 'playful'],
        '👍': ['thumbs'],
        '⭐': ['star'],
        '🔥': ['fire'],
        '🎉': ['party'],
        '😘': ['kiss', 'affection'],
        '☀️': ['sun'],
        '🌙': ['moon'],
        '☁️': ['cloud'],
        '🌈': ['rainbow'],
        '🐱': ['cat'],
        '🐶': ['dog'],
        '🐘': ['elephant'],
        '🦁': ['lion'],
        '🌸': ['flower'],
        '🌳': ['tree'],
        '🚗': ['car'],
        '😍': ['heart_eyes', 'love'],
        '😊': ['blush', 'happy', 'shy'],
        '😏': ['smirk', 'teasing'],
        '😌': ['relieved', 'relaxed'],
        '🤔': ['thinking', 'pondering'],
        '😅': ['sweat_smile'],
        '🙃': ['upside_down'],
        '🤣': ['joy'],
        '😢': ['crying', 'sad_teary'],
        '😴': ['sleepy', 'asleep'],
        '😡': ['angry', 'mad'],
        '😱': ['shocked', 'scream'],
        '😲': ['astonished'],
        '😎': ['sunglasses', 'cool'],
        '🤓': ['nerd', 'studious'],
        '🤦': ['facepalm', 'disbelief'],
        '🤷': ['shrug'],
        '🤗': ['hugging', 'caring'],
        '🥳': ['party_face', 'celebration'],
        '😁': ['grin', 'joyful'],
        '😑': ['annoyed'],
        '😔': ['sad'],
        '😵': ['dizzy', 'stunned'],
        '🤫': ['quiet'],
        '😳': ['embarrassed'],
        '😜': ['tongueOut', 'silly'],
        '🤢': ['sick', 'nauseated'],
        '🤧': ['sneezing'],
        '🤡': ['clown'],
        '💀': ['dead'],
        '🥺': ['pleading', 'begging'],
        '🫠': ['melting', 'overwhelmed'],
        '🫡': ['salute', 'respect'],
        '🔪': ['knife'],
        '🗡️': ['sword'],
        '🤺': ['knight'],
            '👍': 'thumbs_up',
            '👎': 'thumbs_down',
            '👏': 'clap',
            '🙏': 'pray',
            '👌': 'ok',
            '✌️': 'peace',
            '✊': 'fist',
            '✋': 'raised_hand',
            '🤞': 'fingers_crossed',
            '👋': 'wave',
            '🤙': 'call_me',
            '✍️': 'writing_hand',
            '💪': 'muscle',
            '🤝': 'handshake',
            '☝️': 'point_up',
            '👇': 'point_down',
            '👈': 'point_left',
            '👉': 'point_right',
          
            // Food
            '🍎': 'apple',
            '🍌': 'banana',
            '🍇': 'grapes',
            '🍉': 'watermelon',
            '🍊': 'orange',
            '🍍': 'pineapple',
            '🍓': 'strawberry',
            '🍒': 'cherries',
            '🍑': 'peach',
            '🍋': 'lemon',
            '🍕': 'pizza',
            '🍔': 'hamburger',
            '🌭': 'hotdog',
            '🍟': 'fries',
            '🍝': 'spaghetti',
            '🌮': 'taco',
            '🌯': 'burrito',
            '🍿': 'popcorn',
            '🍰': 'cake',
            '🍦': 'icecream',
            '🍩': 'doughnut',
            '🍪': 'cookie',
            '☕': 'coffee',
            '🍵': 'tea',
            '🍷': 'wine_glass',
            '🍺': 'beer',
            '🍸': 'cocktail',
            '🍣': 'sushi',
            '🍜': 'ramen',
          
            // Gen Z expressions
            '💀': 'skull',
            '😭': 'cry',
            '🥺': 'pleads',
            '✨': 'sparkles',
            '🤡': 'clown',
            '👀': 'eyes',
            '💯': 'hundred',
            '💅': 'nails',
            '🫠': 'melting_face',
            '😼': 'smirking_cat',
            '🤤': 'drooling_face',
            '😳': 'flushed_face',
            '🥶': 'cold_face',
            '💥': 'explosion',
            '🤑': 'money_mouth',
            '😵‍💫': 'dizzy',
            '🤠': 'cowboy',
            '🤖': 'robot',
            '🧚': 'fairy',
            '👽': 'alien',
        
                      // Miscellaneous Gen Z additions
                '🍄': 'mushroom',
                '🍃': 'leaf',
                '🔮': 'crystal_ball',
                '👑': 'crown',
                '🖤': 'black_heart',
                '🧠': 'brain',
                '🦋': 'butterfly',
                '👄': 'lips',
                '🍒': 'cherries',
                '🌵': 'cactus',
                '🍑': 'peach',
              
                // Water
                '💧': 'water',
                '💦': 'droplet',
                '💦': 'splash',
                '🌧️': 'rain',
                '🌧️': 'drizzle',
                '🌧️': 'downpour',
                '☔': 'umbrella',
                '☔': 'parasol',
                '🌊': 'wave',
                '🌊': 'ocean',
                '🌊': 'sea',
                '😅': 'sweat',
                '😅': 'perspiration',
                '🚿': 'shower',
                '🛁': 'bath',
                '🏊': 'swimming',
                '🤿': 'snorkeling',
                '🤿': 'dive',
                '🚰': 'faucet',
                '🥤': 'drink',
                '🥤': 'glass',
                '🏊‍♂️': 'pool',
                '🌊': 'lake',
                '🌊': 'river',
                '🐟': 'fish',
                '🐟': 'aquatic',
                '🐳': 'whale',
                '🐳': 'orca',
                '🐬': 'dolphin',
                '🏄': 'surfing',
                '🛶': 'canoe',
                '⛵': 'boat',
                '⛵': 'sail',
              
                // People
                '👤': 'person',
                '👥': 'people',
                '👶': 'baby',
                '🧒': 'child',
                '👦': 'boy',
                '👧': 'girl',
                '👨': 'man',
                '👩': 'woman',
                '👴': 'elderly',
                '👵': 'oldWoman',
                '👪': 'family',
                '👫': 'couple',
                '💏': 'kiss',
                '💑': 'love',
                '🤝': 'handshake',
                '👍': 'thumbsUp',
                '👎': 'thumbsDown',
                '👏': 'clap',
                '🙌': 'raisedHands',
                '🙏': 'pray',
                '💪': 'flex',
                '👌': 'ok',
                '✌️': 'peace',
                '✍️': 'writing',
              
                // Fantasy
                '👼': 'angel',
                '🧚': 'fairy',
                '🧛': 'vampire',
                '🧟': 'zombie',
                '🧜‍♀️': 'mermaid',
                '🧜‍♂️': 'merman',
                '🧝': 'elf',
                '🧞': 'genie',
                '👻': 'ghost',
                '👽': 'alien',
                '🤖': 'robot',
                '🧙': 'wizard',
                '🧙‍♀️': 'witch',
                '🪄': 'magic',
                '🐉': 'dragon',
                '🦄': 'unicorn',
              
                // Animals
                '🐶': 'dog',
                '🐶': 'puppy',
                '🐱': 'cat',
                '🐱': 'kitten',
                '🐭': 'mouse',
                '🐹': 'hamster',
                '🐰': 'rabbit',
                '🐰': 'bunny',
                '🦊': 'fox',
                '🐻': 'bear',
                '🐼': 'panda',
                '🐨': 'koala',
                '🐯': 'tiger',
                '🦁': 'lion',
                '🐮': 'cow',
                '🐷': 'pig',
                '🐸': 'frog',
                '🐒': 'monkey',
                '🐔': 'chicken',
                '🐧': 'penguin',
                '🐦': 'bird',
                '🦅': 'eagle',
                '🦆': 'duck',
                '🦉': 'owl',
                '🐝': 'bee',
                '🐛': 'bug',
                '🦋': 'butterfly',
                '🐌': 'snail',
                '🦀': 'crab',
                '🦞': 'lobster',
                '🦐': 'shrimp',
                '🦑': 'squid',
                '🐟': 'fish',
                '🐳': 'whale',
                '🐬': 'dolphin',
                '🦈': 'shark',
                '🐙': 'octopus',
                '🐢': 'turtle',
                '🐍': 'snake',
              
                // Nature
                '🌳': 'tree',
                '🌲': 'forest',
                '🌴': 'palm',
                '🌵': 'cactus',
                '🌸': 'flower',
                '🌹': 'rose',
                '🌻': 'sunflower',
                '🌼': 'blossom',
                '🌱': 'seedling',
                '🌿': 'herb',
                '☘️': 'shamrock',
                '🍁': 'mapleLeaf',
                '🍂': 'fallenLeaf',
                '🍄': 'mushroom',
                '🌍': 'earth',
                '🌕': 'moon',
                '☀️': 'sun',
                '⭐': 'star',
                '✨': 'sparkles',
                '☁️': 'cloud',
                '⚡': 'lightning',
                '🌪️': 'tornado',
                '🌈': 'rainbow',
                '🌋': 'volcano',
                '🔥': 'fire',
                '🌊': 'ocean'
    
              
     
        
    
      };

    return emojiMap[emoji] || null;
}

// Function to open the modal
function openModal(emoji, emojiName) {
    const emojiElement = document.getElementById('emoji-element');
    const emojiNameElement = document.getElementById('emoji-name');

    // Set the emoji and its name inside the modal
    emojiElement.innerText = emoji; // Display the emoji
    emojiNameElement.innerText = emojiName; // Display the corresponding name

    document.getElementById('emoji-modal').style.display = 'flex'; // Show the modal
}

// Function to close the modal when clicked outside the modal content
function closeModalOnClick(event) {
    // Check if the click is on the background (not on modal content)
    if (event.target === document.getElementById('emoji-modal')) {
        closeModal(); // Close the modal if the background is clicked
    }
}

// Function to close the modal
function closeModal() {
    document.getElementById('emoji-modal').style.display = 'none'; // Hide the modal
}
